### ISSUE TITLE
[Spec Impl] Change Tuvali's VC chunk counter sequence number from 0 based to 1

### ISSUE THREAD

**Issue by tilak-puli** [mosip/tuvali#43]
**Is your feature request related to a problem? Please describe.**
0 based sequence created confusion when looking at the snoop logs. So in Spec it is decided to use 1 based sequence.

**Describe the solution you'd like**
Update the starting number for the check counter and also logic to determine transfer completion.

**Comment by Pragya279** [comment]
This requirement has been moved to Jira.
Link to Jira ticket: https://mosip.atlassian.net/browse/MOSIP-26914

**Comment by vharsh** [comment]
This is already done & merged on 30th May.
